# Generated by Django 4.2.29 on 2026-03-26 15:51

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=50, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('max_systems', models.IntegerField()),
                ('max_tables_per_system', models.IntegerField(default=3)),
                ('max_records_per_table', models.IntegerField(default=50000)),
                ('max_fields_per_table', models.IntegerField(default=200)),
                ('max_storage_mb', models.IntegerField(default=1024)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('features_json', models.TextField(default='[]')),
                ('is_active', models.BooleanField(default=True)),
                ('has_ai_assistant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('security_mode', models.CharField(default='none', max_length=20)),
                ('general_password', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemField',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select'), ('relation', 'Relation'), ('email', 'Email'), ('url', 'URL'), ('phone', 'Phone'), ('time', 'Time'), ('file', 'File')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_display_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_for_fields', to='api.systemfield')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('role', models.CharField(default='user', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('storage_used_bytes', models.BigIntegerField(default=0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('terms_version_accepted', models.IntegerField(default=0)),
                ('session_timeout_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plan')),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('screenshot_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SystemTable',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('custom_style_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.system')),
            ],
            options={
                'unique_together': {('system', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SystemRelationship',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('one_to_one', 'One to One'), ('one_to_many', 'One to Many'), ('many_to_many', 'Many to Many')], default='many_to_many', max_length=20)),
                ('from_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from_field', to='api.systemfield')),
                ('from_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from_table', to='api.systemtable')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.system')),
                ('to_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to_field', to='api.systemfield')),
                ('to_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to_table', to='api.systemtable')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRecord',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.systemtable')),
            ],
        ),
        migrations.CreateModel(
            name='SystemFieldOption',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.systemfield')),
            ],
        ),
        migrations.AddField(
            model_name='systemfield',
            name='related_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_fields', to='api.systemtable'),
        ),
        migrations.AddField(
            model_name='systemfield',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.systemtable'),
        ),
        migrations.CreateModel(
            name='SystemCollaborator',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='api.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('system', 'user')},
            },
        ),
        migrations.AddField(
            model_name='system',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='SecurityAudit',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('event', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.system')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.system')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRecordValue',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.systemfield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.systemrecord')),
            ],
            options={
                'unique_together': {('record', 'field')},
            },
        ),
        migrations.CreateModel(
            name='SystemCollaboratorTable',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_permissions', to='api.systemcollaborator')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.systemtable')),
            ],
            options={
                'unique_together': {('collaborator', 'table')},
            },
        ),
    ]
