# Generated by Django 6.0.4 on 2026-04-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expertise_level',
            field=models.CharField(default='beginner', max_length=20),
        ),
    ]
