# Generated by Django 5.2.15 on 2026-06-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_system_owner_name_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfield',
            name='is_primary_key',
            field=models.BooleanField(default=False),
        ),
    ]
