# Generated by Django 5.2.15 on 2026-07-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_systemcollaborator_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfield',
            name='constraints_json',
            field=models.TextField(default='{}'),
        ),
    ]
